### ISSUE TITLE
Overflow error when entering password on Welcome screen

### ISSUE THREAD

**Issue by Cooljawty** [S1robe/Pocket-Therapist#66]
Trying to enter text to the password field on the welcome page causes the quote box to overflow after the keyboard is opened.

This was tested on the emulator with the following configuration:
 - Emulator Version: 32.1.15.0
 - OS: android 13

# Steps to reproduce
* Open the Welcome Page
* Tap on the "Enter password' field

# Recording of Bug
[emurec0.webm](https://github.com/S1robe/Pocket-Therapist/assets/43480324/023c09fb-09c4-4580-a92e-128074fe0c90)

**Comment by JikoJeans** [comment]
This issue should be remedied after implementing the start button, I have added an expanded widget over the image to allow for the image to reshape after the keyboard is opened up so for now the error should not occur but later functionality might want to be added to make the buttons remain stationary so that after opening the keyboard nothing on the screen moves. After functionality is finished being added to the home screen I will come back and make sure that it looks  visually appealing as the current fix looks like this,
![WelcomePageOpenKeyboard](https://github.com/S1robe/Pocket-Therapist/assets/143761091/a187b84e-0425-496c-a8fc-339ccce8261e)

**Comment by S1robe** [comment]
This is because the PasswordField was not used in the WelcomePage class, thank you for finding this.

**Comment by S1robe** [comment]
@JikoJeans Can you address this please?

**Comment by JikoJeans** [comment]
So in the start button branch I ended up replacing the text buttons with containers so that part should be good. As far as spacing is concerned I can go through and replace the spacers used in the welcome page but that would require me to branch the project again so I will try to address this in my next feature or I can branch off this bug if that is preferred and try fix the spacing issue. If I do branch this bug I can also replace the text field with password field but I would have to add the import for that as well.
